name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.6.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Web tests
        run: npm run web

      - name: Run API tests
        run: npm run api

      - name: Run Android tests
        run: npm run android

      - name: Run Web Accessibility tests
        run: npm run webAccessibility

      - name: Run K6 performance tests
        run: npm run k6

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Display Allure report (optional)
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
